### ISSUE TITLE
07_String_formatieren work wrong

### ISSUE THREAD

**Issue by hbxfwjww** [sechshelme/Lazarus-FreeVision#1]
12_Diverses\07_String_formatieren

Run under Linux, the dialog box shows the string is incorrect, but it is correct under windows.
![centos 64 -2018-05-30-21-49-53](https://user-images.githubusercontent.com/3694262/40724338-69263fe4-6453-11e8-946d-869b84129914.png)

**Comment by sechshelme** [comment]
Dies ist leider ein Bug von Freee-Vision, der bei 64Bit-Versionen von FPC auftritt.
Dabei spielt es keine Rolle, welche OS man verwendet.
Dies habe ich erwähnt, bei Einleitung im ersten Kapitel.

Hier noch der Bug-Report:

https://bugs.freepascal.org/view.php?id=32522

**Comment by fsb4000** [comment]
if you will write:   
```
params: record
    s1, s2: PString;
    i1, i2: IntPtr;
 end;
```
it will work for both versions fpc 32 and 64:
![freevision](https://user-images.githubusercontent.com/4289847/76679784-d1e4ca80-6615-11ea-9425-7d071da37318.png)

**Comment by sechshelme** [comment]
@fsb4000 

Vielen Danke für den Tip. 
Nun ist dieses Problem auch behoben.
Ich habe das Tutorial angepasst.

**Comment by fsb4000** [comment]
@sechshelme You're welcome!

**Comment by sechshelme** [comment]
So wie ich sehe, wurde in den Sourcen, einige LongInt durch PtrStr ausgetauscht.

https://svn.freepascal.org/cgi-bin/viewvc.cgi/trunk/packages/fv/src/?sortby=rev&sortdir=down
