### ISSUE TITLE
source code missing for 10_Hello_World

### ISSUE THREAD

**Issue by arne-cl** [sechshelme/Lazarus-FreeVision#2]
Vielen Dank für die Erstellung des Tutorials.
Ironischerweise fehlt ausgerechnet auf der "Hello World"-Seite der Quelltext.

**Comment by sechshelme** [comment]
Dies sollte nun auch gehen.   ;-)

**Comment by arne-cl** [comment]
VIelen Dank!

**Comment by sechshelme** [comment]
Danke auch dir !
Nur wen man Feedback bekommt, kann man etwas verbessern. ;-)
